export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";

export const GET_PRODUCT_OF_SELLER = "GET_PRODUCT_OF_SELLER";
export const DELETE_PRODUCT_OF_SELLER = "DELETE_PRODUCT_OF_SELLER";
export const ADD_PRODUCT_OF_SELLER = "ADD_PRODUCT_OF_SELLER";
export const EDIT_PRODUCT_OF_SELLER = "EDIT_PRODUCT_OF_SELLER";

export const GET_PRODUCT_IN_BUYER_CART = "GET_PRODUCT_IN_BUYER_CART";
export const ADD_PRODUCT_IN_BUYER_CART = "ADD_PRODUCT_IN_BUYER_CART";
export const DELETE_PRODUCT_IN_BUYER_CART = "DELETE_PRODUCT_IN_BUYER_CART";
